/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/anime/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get anime by ID
     * @description Get anime by ID
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.AnimeWithMetadataResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/{id}/banner': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get anime banner
     * @description Get anime banner
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.BannerResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/{id}/characters': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get anime characters
     * @description Get anime characters
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.CharacterResponse'][]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/{id}/episodes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get anime episodes
     * @description Get anime episodes
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.EpisodeResponse'][]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/{id}/episodes/{episodeID}/servers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get episode servers
     * @description Get episode servers
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          id: string
          /** @description Episode ID */
          episodeID: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.EpisodeServerResponse'][]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/{id}/episodes/servers/{serverID}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get episode stream data
     * @description Get episode stream data
     */
    get: {
      parameters: {
        query: {
          /** @description Server name */
          server: string
          /** @description Stream type */
          type: string
        }
        header?: never
        path: {
          /** @description Anime ID */
          id: string
          /** @description Server ID */
          serverID: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.StreamingDataResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/{id}/franchise': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get anime franchise relations
     * @description Get anime franchise relations
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.RelationsResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/{id}/full': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get full anime details
     * @description Get all anime details in a single response including anime data, banner, trailer, episodes, franchise, characters, and library status (if authenticated)
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.AnimeFullResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/{id}/trailer': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get anime trailer
     * @description Get anime trailer
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.TrailerResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/{id}/variations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get anime variations
     * @description Get all variations of an anime (same MAL ID)
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.AnimeResponse'][]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/listings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get anime catalog with optional library information
     * @description Get anime catalog. When authenticated, includes library status. Supports library-only filtering and search.
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number (default: 1) */
          page?: number
          /** @description Number of items per page (default: 30, max: 100) */
          itemsPerPage?: number
          /** @description Search anime by name */
          search?: string
          /** @description Filter by genres (repeat for multiple) */
          genres?: string[]
          /** @description Genre matching mode: 'any' (default) or 'all' */
          genresMode?: 'any' | 'all'
          /** @description Filter by seasons (repeat for multiple) */
          seasons?: ('winter' | 'spring' | 'summer' | 'fall' | 'unknown')[]
          /** @description Filter by specific years (repeat for multiple) */
          years?: number[]
          /** @description Filter by minimum year (inclusive) */
          yearMin?: number
          /** @description Filter by maximum year (inclusive) */
          yearMax?: number
          /** @description Sort field */
          sortBy?:
            | 'ename'
            | 'jname'
            | 'season'
            | 'year'
            | 'relevance'
            | 'updated_at'
            | 'anime_updated_at'
            | 'library_updated_at'
          /** @description Sort order: 'asc' or 'desc' (default: 'desc') */
          sortOrder?: 'asc' | 'desc'
          /** @description Only show anime in user's library (requires authentication) */
          inLibraryOnly?: boolean
          /** @description Filter by library status (requires authentication) */
          status?: 'watching' | 'completed' | 'planning' | 'dropped' | 'paused'
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Anime catalog with optional library information */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.AnimeWithLibraryListResponse']
          }
        }
        /** @description Invalid request parameters */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Authentication required for library features */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/listings/genres': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get list of anime genres
     * @description Get list of anime genres
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': string[]
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/listings/genres/{genre}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get anime by genre
     * @description Get anime by genre
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number
          /** @description Number of items per page */
          itemsPerPage?: number
        }
        header?: never
        path: {
          /** @description Genre name */
          genre: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.AnimeListResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/listings/genres/previews': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get genre previews
     * @description Get 6 preview image URLs for each genre
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.GenrePreview'][]
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/listings/popular': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get popular anime
     * @description Get popular anime
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.AnimeResponse'][]
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/listings/random': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get random anime
     * @description Get random anime
     */
    get: {
      parameters: {
        query?: {
          /** @description Optional genre filter */
          genre?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.AnimeResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/listings/recently-updated': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get recently updated anime
     * @description Get recently updated anime
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number
          /** @description Number of items per page */
          itemsPerPage?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.AnimeListResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/listings/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search anime
     * @description Search anime
     */
    get: {
      parameters: {
        query: {
          /** @description Search query (minimum 3 characters) */
          q: string
          /** @description Optional genre filter (minimum 3 characters) */
          genre?: string
          /** @description Page number */
          page?: number
          /** @description Number of items per page */
          itemsPerPage?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.AnimeListResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/listings/seasonal': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get seasonal anime
     * @description Get seasonal anime
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.SeasonalAnimeResponse'][]
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/listings/seasons': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get anime by season and/or year
     * @description Get anime by season and/or year
     */
    get: {
      parameters: {
        query?: {
          /** @description Season filter */
          season?: string
          /** @description Year filter */
          year?: number
          /** @description Page number */
          page?: number
          /** @description Number of items per page */
          itemsPerPage?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.AnimeListResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/anime/listings/trending': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get trending anime
     * @description Get trending anime
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.AnimeResponse'][]
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/forget-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Request password reset
     * @description Request password reset
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description User email */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.ForgetPasswordRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ValidationErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * User login
     * @description User login
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description User credentials */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.LoginRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            /** @description Session cookie */
            'Set-Cookie'?: string
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.UserResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ValidationErrorResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * User logout
     * @description User logout
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get current user information
     * @description Get current user information
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.UserResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/oauth/{provider}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Start OAuth authentication
     * @description Start OAuth authentication
     */
    get: {
      parameters: {
        query?: {
          /** @description Redirect URL after authentication */
          redirect?: string
        }
        header?: never
        path: {
          /** @description OAuth provider */
          provider: 'anilist' | 'myanimelist'
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Found */
        302: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/oauth/{provider}/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * OAuth callback endpoint
     * @description OAuth callback endpoint
     */
    get: {
      parameters: {
        query: {
          /** @description OAuth authorization code */
          code: string
          /** @description OAuth state parameter */
          state: string
        }
        header?: never
        path: {
          /** @description OAuth provider */
          provider: 'anilist' | 'myanimelist'
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Found */
        302: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/providers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get connected OAuth providers
     * @description Get connected OAuth providers
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': string[]
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/providers/{provider}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Disconnect OAuth provider
     * @description Disconnect OAuth provider
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Provider name */
          provider: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/reset-password/{token}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Reset password
     * @description Reset password
     */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Password reset token */
          token: string
        }
        cookie?: never
      }
      /** @description New password */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.ResetPasswordRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ValidationErrorResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/u/{token}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get user by password reset token
     * @description Get user by password reset token
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Password reset token */
          token: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ChangePasswordTokenResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/characters/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get character by ID
     * @description Get detailed character information by MAL ID
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Character MAL ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.CharacterFullResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/characters/va/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get person by ID
     * @description Get detailed person (voice actor) information by MAL ID
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Person MAL ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.PersonFullResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Simple health check
     * @description Check if the API service is running
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['handlers.HealthCheckResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/z': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Comprehensive health check
     * @description Check the health of all services and external APIs
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['handlers.HealthResponse']
          }
        }
        /** @description Service Unavailable */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['handlers.HealthResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/home': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get home page data
     * @description Get all home page data in a single response including trending, popular, recently updated, seasonal anime, and user library sections (if authenticated)
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.HomeResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/library': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get user's anime library
     * @description Get user's anime library
     */
    get: {
      parameters: {
        query: {
          /** @description Library status filter */
          status: 'planning' | 'watching' | 'completed' | 'dropped' | 'paused'
          /** @description Page number */
          page?: number
          /** @description Number of items per page */
          itemsPerPage?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.LibraryListResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    /**
     * Clear user's library
     * @description Clear user's library
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/library/{animeID}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get anime status in library
     * @description Get anime status in library
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          animeID: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.LibraryResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    /**
     * Update anime in library
     * @description Update anime in library
     */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          animeID: string
        }
        cookie?: never
      }
      requestBody: components['requestBodies']['models.LibraryRequest']
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.LibraryResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ValidationErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    /**
     * Add anime to library
     * @description Add anime to library
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          animeID: string
        }
        cookie?: never
      }
      requestBody: components['requestBodies']['models.LibraryRequest']
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.LibraryResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ValidationErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    /**
     * Remove anime from library
     * @description Remove anime from library
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Anime ID */
          animeID: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/library/{animeID}/switch/{variationID}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Switch library entry to different variation
     * @description Switch user's library entry from current anime to a variation (same MAL ID)
     */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Current Anime ID */
          animeID: string
          /** @description Target Variation Anime ID */
          variationID: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.LibraryResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/library/continue-watching': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get continue watching list
     * @description Get continue watching list
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number
          /** @description Number of items per page */
          itemsPerPage?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.LibraryListResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/library/import': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Import library from external provider
     * @description Import library from external provider
     */
    post: {
      parameters: {
        query: {
          /** @description External provider to import from */
          provider: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ImportJobResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/library/import/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get library import status
     * @description Get library import status
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Import job ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.LibraryImportJobResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/library/planning': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get plan to watch list
     * @description Get plan to watch list
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number
          /** @description Number of items per page */
          itemsPerPage?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.LibraryListResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/library/stats': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get library statistics
     * @description Get library statistics including watching, planning, and completed counts
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.LibraryStatsResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get user settings
     * @description Get user settings
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.SettingsResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    /**
     * Save user settings
     * @description Save user settings
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Settings object */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.SettingsRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.SettingsResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ValidationErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/themes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get available themes
     * @description Get available themes
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.Theme'][]
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Update user information
     * @description Update user information
     */
    put: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description User object */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.UpdateUserRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.UserResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ValidationErrorResponse']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    /**
     * Create new user
     * @description Create new user
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description User object */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.CreateUserRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.UserResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ValidationErrorResponse']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    /**
     * Delete user account
     * @description Delete user account
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Password object */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.DeleteUserRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ValidationErrorResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/image': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Update user profile picture
     * @description Update user profile picture
     */
    put: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'multipart/form-data': {
            /**
             * Format: binary
             * @description Image file
             */
            image: string
          }
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    post?: never
    /**
     * Remove user profile picture
     * @description Remove user profile picture
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Update user password
     * @description Update user password
     */
    put: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Password object */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.UpdatePasswordRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ValidationErrorResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['models.ErrorResponse']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    'handlers.HealthCheckResponse': {
      /** @example api */
      service?: string
      /** @example healthy */
      status?: string
      /** @example 2023-01-01T00:00:00Z */
      timestamp?: string
    }
    'handlers.HealthResponse': {
      services?: {
        [key: string]: string
      }
      /** @example healthy */
      status?: string
      /** @example 2023-01-01T00:00:00Z */
      timestamp?: string
      /** @example 1.0.0 */
      version?: string
    }
    'models.AnimeFullResponse': {
      anime: components['schemas']['models.AnimeWithMetadataResponse']
      banner?: components['schemas']['models.BannerResponse']
      characters?: components['schemas']['models.CharacterResponse'][]
      episodes?: components['schemas']['models.EpisodeResponse'][]
      franchise?: components['schemas']['models.RelationsResponse']
      libraryStatus?: components['schemas']['models.LibraryResponse']
      trailer?: components['schemas']['models.TrailerResponse']
      variations?: components['schemas']['models.AnimeResponse'][]
    }
    'models.AnimeListResponse': {
      items: components['schemas']['models.AnimeResponse'][]
      pageInfo: components['schemas']['models.PageInfo']
    }
    'models.AnimeMetadataResponse': {
      /** @example 2023-09-30 */
      airingEndDate: string
      /** @example 2023-04-01 */
      airingStartDate: string
      /** @example finished_airing */
      airingStatus: string
      /** @example 24 */
      avgEpisodeDuration: number
      /** @example Humanity fights for survival against giant humanoid Titans. */
      description: string
      /** @example https://example.com/main.jpg */
      mainPictureUrl: string
      /** @example 12345 */
      malId: number
      /** @example 9 */
      mean: number
      /** @example TV */
      mediaType: string
      /** @example 1 */
      popularity: number
      /** @example 5 */
      rank: number
      /** @example R - 17+ (violence & profanity) */
      rating: string
      /** @example 500000 */
      scoringUsers: number
      /** @example spring */
      season: string
      /** @example 2023 */
      seasonYear: number
      /** @example Manga */
      source: string
      /** @example Studio Pierrot */
      studio: string
      /** @example 25 */
      totalEpisodes: number
      /** @example https://www.youtube.com/embed/abc123 */
      trailerEmbedUrl: string
    }
    'models.AnimeResponse': {
      /** @example 67890 */
      anilistId?: number
      /** @example Attack on Titan */
      ename?: string
      /** @example Action, Drama */
      genre: string
      /** @example V1StGXR8Z5jdHi6B */
      id: string
      /** @example https://example.com/anime/image.jpg */
      imageUrl: string
      /** @example 進撃の巨人 */
      jname?: string
      /** @example 25 */
      lastEpisode?: number
      /** @example 12345 */
      malId?: number
      /** @example spring */
      season: string
      /** @example 2023 */
      seasonYear?: number
    }
    'models.AnimeWithLibraryListResponse': {
      items: components['schemas']['models.AnimeWithLibraryResponse'][]
      pageInfo: components['schemas']['models.PageInfo']
    }
    'models.AnimeWithLibraryResponse': {
      /** @example 67890 */
      anilistId?: number
      /** @example Attack on Titan */
      ename?: string
      /** @example Action, Drama */
      genre: string
      /** @example V1StGXR8Z5jdHi6B */
      id: string
      /** @example https://example.com/anime/image.jpg */
      imageUrl: string
      /** @example 進撃の巨人 */
      jname?: string
      /** @example 25 */
      lastEpisode?: number
      library?: components['schemas']['models.LibraryInfo']
      /** @example 12345 */
      malId?: number
      /** @example spring */
      season: string
      /** @example 2023 */
      seasonYear?: number
    }
    'models.AnimeWithMetadataResponse': {
      /** @example 67890 */
      anilistId?: number
      /** @example Attack on Titan */
      ename?: string
      /** @example Action, Drama */
      genre: string
      /** @example V1StGXR8Z5jdHi6B */
      id: string
      /** @example https://example.com/anime/image.jpg */
      imageUrl: string
      /** @example 進撃の巨人 */
      jname?: string
      /** @example 25 */
      lastEpisode?: number
      /** @example 12345 */
      malId?: number
      metadata?: components['schemas']['models.AnimeMetadataResponse']
      /** @example spring */
      season: string
      /** @example 2023 */
      seasonYear?: number
    }
    'models.BannerResponse': {
      /** @example https://example.com/banner.jpg */
      url: string
    }
    'models.ChangePasswordTokenResponse': {
      /** @example 1700000000 */
      expires_at?: number
      user?: components['schemas']['models.UserResponse']
    }
    'models.CharacterAnimeResponse': {
      anime: components['schemas']['models.AnimeResponse']
      /** @example Main */
      role: string
    }
    'models.CharacterFullResponse': {
      /** @example A determined young man who seeks freedom... */
      about?: string
      anime: components['schemas']['models.CharacterAnimeResponse'][]
      /** @example 10000 */
      favorites: number
      /** @example https://example.com/character.jpg */
      image: string
      /** @example 1 */
      malId: number
      /** @example Eren Yeager */
      name: string
      /** @example エレン・イェーガー */
      nameKanji?: string
      /**
       * @example [
       *       "Eren",
       *       "Tatakae"
       *     ]
       */
      nicknames?: string[]
      voices: components['schemas']['models.CharacterVoiceResponse'][]
    }
    'models.CharacterResponse': {
      /** @example 10000 */
      favorites: number
      /** @example https://example.com/character.jpg */
      image: string
      /** @example 1 */
      malId: number
      /** @example Eren Yeager */
      name: string
      /** @example Main */
      role: string
    }
    'models.CharacterVoicePersonResponse': {
      /** @example https://example.com/voice-actor.jpg */
      image?: string
      /** @example 123 */
      malId: number
      /** @example Yuki Kaji */
      name: string
    }
    'models.CharacterVoiceResponse': {
      /** @example Japanese */
      language: string
      person: components['schemas']['models.CharacterVoicePersonResponse']
    }
    'models.CreateUserRequest': {
      /** @example john@example.com */
      email: string
      /** @example password123 */
      password: string
      /** @example johndoe */
      username: string
    }
    'models.DeleteUserRequest': {
      /** @example password123 */
      password: string
    }
    'models.EpisodeResponse': {
      /** @example V1StGXR8Z5jdHi6B */
      id: string
      /** @example false */
      isFiller: boolean
      /** @example 1 */
      number: number
      /** @example The Attack Titan */
      title: string
    }
    'models.EpisodeServerResponse': {
      /** @example V1StGXR8Z5jdHi6B */
      serverId: string
      /** @example vidstreaming */
      serverName: string
      /** @example sub */
      type: string
    }
    'models.ErrorResponse': {
      /** @example Invalid request */
      error: string
    }
    'models.ForgetPasswordRequest': {
      /** @example user@example.com */
      email: string
    }
    'models.GenrePreview': {
      name?: string
      previews?: string[]
    }
    'models.HomeResponse': {
      continueWatching?: components['schemas']['models.LibraryResponse'][]
      featuredAnime?: components['schemas']['models.AnimeWithMetadataResponse']
      planning?: components['schemas']['models.LibraryResponse'][]
      popular: components['schemas']['models.AnimeResponse'][]
      recentlyUpdated: components['schemas']['models.AnimeResponse'][]
      seasonal: components['schemas']['models.SeasonalAnimeResponse'][]
      trending: components['schemas']['models.AnimeResponse'][]
    }
    'models.ImportJobResponse': {
      /** @example V1StGXR8Z5jdHi6BmyT23 */
      id: string
    }
    'models.LibraryImportJobResponse': {
      /** @example 2023-01-01T00:00:00Z */
      completedAt: string
      /** @example 2023-01-01T00:00:00Z */
      createdAt: string
      /** @example V1StGXR8Z5jdHi6B */
      id: string
      /** @example pending */
      status: components['schemas']['models.LibraryImportStatus']
      /** @example 2023-01-01T00:00:00Z */
      updatedAt: string
      /** @example V1StGXR8Z5jdHi6B */
      userId: string
    }
    /** @enum {string} */
    'models.LibraryImportStatus': 'pending' | 'in_progress' | 'completed' | 'failed'
    'models.LibraryInfo': {
      /** @example V1StGXR8Z5jdHi6B */
      id: string
      /** @example watching */
      status: components['schemas']['models.LibraryStatus']
      /** @example 2023-01-01T00:00:00Z */
      updatedAt: string
      /** @example 12 */
      watchedEpisodes: number
    }
    'models.LibraryListResponse': {
      items: components['schemas']['models.LibraryResponse'][]
      pageInfo: components['schemas']['models.PageInfo']
    }
    'models.LibraryRequest': {
      /** @example watching */
      status: components['schemas']['models.LibraryStatus']
      /** @example 12 */
      watchedEpisodes?: number
    }
    'models.LibraryResponse': {
      anime: components['schemas']['models.AnimeResponse']
      /** @example V1StGXR8Z5jdHi6B */
      animeId: string
      /** @example 2023-01-01T00:00:00Z */
      createdAt: string
      /** @example V1StGXR8Z5jdHi6B */
      id: string
      /** @example watching */
      status: components['schemas']['models.LibraryStatus']
      /** @example 2023-01-01T00:00:00Z */
      updatedAt: string
      /** @example V1StGXR8Z5jdHi6B */
      userId: string
      /** @example 12 */
      watchedEpisodes: number
    }
    'models.LibraryStatsResponse': {
      /** @example 150 */
      completed: number
      /** @example 10 */
      planning: number
      /** @example 25 */
      watching: number
    }
    /** @enum {string} */
    'models.LibraryStatus': 'planning' | 'watching' | 'completed' | 'dropped' | 'paused'
    'models.LoginRequest': {
      /** @example user@example.com */
      email: string
      /** @example password123 */
      password: string
    }
    'models.PageInfo': {
      currentPage: number
      hasNextPage: boolean
      hasPrevPage: boolean
      totalPages: number
    }
    'models.PersonAnimeResponse': {
      anime: components['schemas']['models.AnimeResponse']
      /** @example Main */
      position: string
    }
    'models.PersonCharacterResponse': {
      anime: components['schemas']['models.AnimeResponse']
      character: components['schemas']['models.CharacterResponse']
      /** @example Main */
      role: string
    }
    'models.PersonFullResponse': {
      /** @example Birthplace: Chiba Prefecture, Japan... */
      about?: string
      /**
       * @example [
       *       "Wakayama Shion"
       *     ]
       */
      alternateNames?: string[]
      anime: components['schemas']['models.PersonAnimeResponse'][]
      /** @example 1998-02-10T00:00:00+00:00 */
      birthday?: string
      characters: components['schemas']['models.PersonCharacterResponse'][]
      /** @example 若山 */
      familyName?: string
      /** @example 1502 */
      favorites: number
      /** @example 詩音 */
      givenName?: string
      /** @example https://example.com/person.jpg */
      image: string
      /** @example 35511 */
      malId: number
      /** @example Shion Wakayama */
      name: string
    }
    'models.RelationsResponse': {
      related: components['schemas']['models.AnimeResponse'][]
      watchOrder: components['schemas']['models.AnimeResponse'][]
    }
    'models.ResetPasswordRequest': {
      /** @example newpassword123 */
      password: string
    }
    'models.SeasonalAnimeResponse': {
      anime: components['schemas']['models.AnimeResponse']
      /** @example https://example.com/banner.jpg */
      bannerImageUrl: string
      /** @example New seasonal anime description */
      description: string
      /** @example 12 */
      episodes: number
      /** @example V1StGXR8Z5jdHi6B */
      id: string
      /** @example 1672531200 */
      startDate: number
      /** @example TV */
      type: string
    }
    'models.SegmentResponse': {
      /** @example 180 */
      end: number
      /** @example 90 */
      start: number
    }
    'models.SettingsRequest': {
      /** @example true */
      autoNextEpisode?: boolean
      /** @example false */
      autoPlayEpisode?: boolean
      /** @example true */
      autoResumeEpisode?: boolean
      /** @example false */
      incognitoMode?: boolean
      /** @example 1 */
      themeId?: number
    }
    'models.SettingsResponse': {
      /** @example true */
      autoNextEpisode: boolean
      /** @example false */
      autoPlayEpisode: boolean
      /** @example true */
      autoResumeEpisode: boolean
      /** @example false */
      incognitoMode: boolean
      theme: components['schemas']['models.Theme']
      /** @example V1StGXR8Z5jdHi6B */
      userId: string
    }
    'models.StreamingDataResponse': {
      intro: components['schemas']['models.SegmentResponse']
      outro: components['schemas']['models.SegmentResponse']
      source: components['schemas']['models.StreamingSourceResponse']
      tracks: components['schemas']['models.TrackResponse'][]
    }
    'models.StreamingSourceResponse': {
      /** @example https://example.com/stream.m3u8 */
      hls?: string
      /** @example https://example.com/embed/abc123 */
      iframe: string
      /** @example /proxy/{server}/{encodedUrl} */
      proxyHls?: string
    }
    'models.Theme': {
      /** @example theme-default */
      className: string
      /** @example The default Aniways theme. */
      description: string
      /** @example 1 */
      id: number
      /** @example Default */
      name: string
    }
    'models.TrackResponse': {
      /** @example true */
      default: boolean
      /** @example captions */
      kind: string
      /** @example English */
      label: string
      /** @example https://example.com/subtitles.vtt */
      raw: string
      /** @example /proxy/{server}/{encodedUrl} */
      url: string
    }
    'models.TrailerResponse': {
      /** @example https://www.youtube.com/embed/abc123 */
      trailer: string
    }
    'models.UpdatePasswordRequest': {
      /** @example newpassword123 */
      newPassword: string
      /** @example oldpassword123 */
      oldPassword: string
    }
    'models.UpdateUserRequest': {
      /** @example john@example.com */
      email: string
      /** @example johndoe */
      username: string
    }
    'models.UserResponse': {
      /** @example 2023-01-01T00:00:00Z */
      createdAt: string
      /** @example john@example.com */
      email: string
      /** @example V1StGXR8Z5jdHi6B */
      id: string
      /** @example https://res.cloudinary.com/example/avatar.jpg */
      profilePicture?: string
      /** @example 2023-01-01T00:00:00Z */
      updatedAt: string
      /** @example johndoe */
      username: string
    }
    'models.ValidationErrorResponse': {
      /**
       * @example {
       *       "email": "invalid email format"
       *     }
       */
      details?: {
        [key: string]: string
      }
      /** @example Validation failed */
      error: string
    }
  }
  responses: never
  parameters: never
  requestBodies: {
    /** @description Library object */
    'models.LibraryRequest': {
      content: {
        'application/json': components['schemas']['models.LibraryRequest']
      }
    }
  }
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
