// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AiringStatus string

const (
	AiringStatusFinishedAiring  AiringStatus = "finished_airing"
	AiringStatusCurrentlyAiring AiringStatus = "currently_airing"
	AiringStatusNotYetAired     AiringStatus = "not_yet_aired"
	AiringStatusUnknown         AiringStatus = "unknown"
)

func (e *AiringStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AiringStatus(s)
	case string:
		*e = AiringStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AiringStatus: %T", src)
	}
	return nil
}

type NullAiringStatus struct {
	AiringStatus AiringStatus
	Valid        bool // Valid is true if AiringStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAiringStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AiringStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AiringStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAiringStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AiringStatus), nil
}

type LibraryActions string

const (
	LibraryActionsAddEntry       LibraryActions = "add_entry"
	LibraryActionsUpdateProgress LibraryActions = "update_progress"
	LibraryActionsUpdateStatus   LibraryActions = "update_status"
	LibraryActionsDeleteEntry    LibraryActions = "delete_entry"
)

func (e *LibraryActions) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LibraryActions(s)
	case string:
		*e = LibraryActions(s)
	default:
		return fmt.Errorf("unsupported scan type for LibraryActions: %T", src)
	}
	return nil
}

type NullLibraryActions struct {
	LibraryActions LibraryActions
	Valid          bool // Valid is true if LibraryActions is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLibraryActions) Scan(value interface{}) error {
	if value == nil {
		ns.LibraryActions, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LibraryActions.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLibraryActions) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LibraryActions), nil
}

type LibraryImportStatus string

const (
	LibraryImportStatusPending    LibraryImportStatus = "pending"
	LibraryImportStatusInProgress LibraryImportStatus = "in_progress"
	LibraryImportStatusCompleted  LibraryImportStatus = "completed"
	LibraryImportStatusFailed     LibraryImportStatus = "failed"
)

func (e *LibraryImportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LibraryImportStatus(s)
	case string:
		*e = LibraryImportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LibraryImportStatus: %T", src)
	}
	return nil
}

type NullLibraryImportStatus struct {
	LibraryImportStatus LibraryImportStatus
	Valid               bool // Valid is true if LibraryImportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLibraryImportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LibraryImportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LibraryImportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLibraryImportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LibraryImportStatus), nil
}

type LibraryStatus string

const (
	LibraryStatusPlanning  LibraryStatus = "planning"
	LibraryStatusWatching  LibraryStatus = "watching"
	LibraryStatusCompleted LibraryStatus = "completed"
	LibraryStatusDropped   LibraryStatus = "dropped"
	LibraryStatusPaused    LibraryStatus = "paused"
)

func (e *LibraryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LibraryStatus(s)
	case string:
		*e = LibraryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LibraryStatus: %T", src)
	}
	return nil
}

type NullLibraryStatus struct {
	LibraryStatus LibraryStatus
	Valid         bool // Valid is true if LibraryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLibraryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LibraryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LibraryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLibraryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LibraryStatus), nil
}

type LibrarySyncStatus string

const (
	LibrarySyncStatusPending LibrarySyncStatus = "pending"
	LibrarySyncStatusSuccess LibrarySyncStatus = "success"
	LibrarySyncStatusFailed  LibrarySyncStatus = "failed"
	LibrarySyncStatusSkipped LibrarySyncStatus = "skipped"
)

func (e *LibrarySyncStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LibrarySyncStatus(s)
	case string:
		*e = LibrarySyncStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LibrarySyncStatus: %T", src)
	}
	return nil
}

type NullLibrarySyncStatus struct {
	LibrarySyncStatus LibrarySyncStatus
	Valid             bool // Valid is true if LibrarySyncStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLibrarySyncStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LibrarySyncStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LibrarySyncStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLibrarySyncStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LibrarySyncStatus), nil
}

type Provider string

const (
	ProviderMyanimelist Provider = "myanimelist"
	ProviderAnilist     Provider = "anilist"
)

func (e *Provider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Provider(s)
	case string:
		*e = Provider(s)
	default:
		return fmt.Errorf("unsupported scan type for Provider: %T", src)
	}
	return nil
}

type NullProvider struct {
	Provider Provider
	Valid    bool // Valid is true if Provider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProvider) Scan(value interface{}) error {
	if value == nil {
		ns.Provider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Provider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Provider), nil
}

type Rating string

const (
	RatingPg13    Rating = "pg_13"
	RatingR       Rating = "r"
	RatingValue2  Rating = "r+"
	RatingG       Rating = "g"
	RatingPg      Rating = "pg"
	RatingRx      Rating = "rx"
	RatingUnknown Rating = "unknown"
)

func (e *Rating) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Rating(s)
	case string:
		*e = Rating(s)
	default:
		return fmt.Errorf("unsupported scan type for Rating: %T", src)
	}
	return nil
}

type NullRating struct {
	Rating Rating
	Valid  bool // Valid is true if Rating is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRating) Scan(value interface{}) error {
	if value == nil {
		ns.Rating, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Rating.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRating) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Rating), nil
}

type Season string

const (
	SeasonWinter  Season = "winter"
	SeasonSpring  Season = "spring"
	SeasonSummer  Season = "summer"
	SeasonFall    Season = "fall"
	SeasonUnknown Season = "unknown"
)

func (e *Season) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Season(s)
	case string:
		*e = Season(s)
	default:
		return fmt.Errorf("unsupported scan type for Season: %T", src)
	}
	return nil
}

type NullSeason struct {
	Season Season
	Valid  bool // Valid is true if Season is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSeason) Scan(value interface{}) error {
	if value == nil {
		ns.Season, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Season.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSeason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Season), nil
}

type Anime struct {
	ID           string
	Ename        string
	Jname        string
	ImageUrl     string
	Genre        string
	HiAnimeID    string
	MalID        pgtype.Int4
	AnilistID    pgtype.Int4
	LastEpisode  int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	SearchVector string
	Season       Season
	SeasonYear   int32
	GenresArr    []string
}

type AnimeMetadatum struct {
	MalID              int32
	Description        pgtype.Text
	MainPictureUrl     pgtype.Text
	MediaType          pgtype.Text
	Rating             Rating
	AiringStatus       AiringStatus
	AvgEpisodeDuration pgtype.Int4
	TotalEpisodes      pgtype.Int4
	Studio             pgtype.Text
	Rank               pgtype.Int4
	Mean               pgtype.Float8
	Scoringusers       pgtype.Int4
	Popularity         pgtype.Int4
	AiringStartDate    pgtype.Text
	AiringEndDate      pgtype.Text
	Source             pgtype.Text
	TrailerEmbedUrl    pgtype.Text
	SeasonYear         pgtype.Int4
	Season             Season
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

type ExternalLibrarySync struct {
	UserID    string
	AnimeID   string
	Provider  Provider
	Action    LibraryActions
	Payload   []byte
	Status    LibrarySyncStatus
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Library struct {
	ID              string
	UserID          string
	AnimeID         string
	Status          LibraryStatus
	WatchedEpisodes int32
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type LibraryImportJob struct {
	ID           string
	UserID       string
	Provider     Provider
	Status       LibraryImportStatus
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	CompletedAt  pgtype.Timestamp
}

type OauthToken struct {
	ID           string
	UserID       string
	Token        string
	RefreshToken string
	Provider     Provider
	ExpiresAt    pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
}

type ResetPasswordToken struct {
	Token     string
	UserID    string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type Session struct {
	ID        string
	UserID    string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type Setting struct {
	UserID            string
	AutoNextEpisode   bool
	AutoPlayEpisode   bool
	AutoResumeEpisode bool
	IncognitoMode     bool
	ThemeID           int32
}

type Theme struct {
	ID          int32
	Name        string
	ThemeClass  string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type User struct {
	ID             string
	Username       string
	Email          string
	PasswordHash   string
	ProfilePicture pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
